/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rw.gov.Dao.AccountDao;
import rw.gov.Model.Account;

/**
 *
 * @author andre
 */
public class NewAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */

    
    public NewAccount() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
        maleText.setActionCommand("Male");
        femaleText.setActionCommand("Female");
        
//        this.accountNumber = accountNumber;
//        
//        youraccount.setText(String.valueOf(accountNumber));

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        accountNoText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pinText = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        maleText = new javax.swing.JRadioButton();
        femaleText = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        telText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        accountTypeText = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        openDateText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        newAccount = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setPreferredSize(new java.awt.Dimension(620, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Create New Account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("First Name :");

        jLabel6.setText("Last Name :");

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Account No. :");

        jLabel8.setText("Pin :");

        jLabel9.setText("Gender :");

        buttonGroup1.add(maleText);
        maleText.setText("Male");

        buttonGroup1.add(femaleText);
        femaleText.setText("Female");

        jLabel10.setText("Tel No. :");

        jLabel11.setText("Account Type :");

        accountTypeText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Saving", "Checking", " " }));

        jLabel12.setText("Address :");

        jLabel13.setText("Opening Date :");

        jLabel14.setText("Amount :");

        newAccount.setBackground(new java.awt.Color(102, 0, 102));
        newAccount.setForeground(new java.awt.Color(255, 255, 255));
        newAccount.setText("Create");
        newAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountActionPerformed(evt);
            }
        });

        jLabel15.setText("Email :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .addComponent(lastNameText)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(accountNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(166, 166, 166)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newAccount)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(telText)
                                        .addComponent(accountTypeText, 0, 88, Short.MAX_VALUE)
                                        .addComponent(addressText)
                                        .addComponent(openDateText)
                                        .addComponent(amountText))))))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pinText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(maleText)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femaleText)))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(telText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(accountTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accountNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(openDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(maleText)
                    .addComponent(femaleText)
                    .addComponent(jLabel14)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newAccount)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 580, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 720, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void newAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountActionPerformed
        // TODO add your handling code here:
        Account theAccount = new Account();

    String firstName = firstNameText.getText();
    String lastName = lastNameText.getText();
    String telNo = telText.getText();
    String accountNo = accountNoText.getText();    
    char[] pin = pinText.getPassword();
    String gender = buttonGroup1.getSelection() != null ? buttonGroup1.getSelection().getActionCommand() : null;
    String address = addressText.getText();
    String accountType = accountTypeText.getSelectedItem() != null ? accountTypeText.getSelectedItem().toString() : null;
    String openDate = openDateText.getText();
    String amountString = amountText.getText();
    String email = emailText.getText();

    if (firstName.isEmpty() || lastName.isEmpty() || telNo.isEmpty() || accountNo.isEmpty() || String.valueOf(pin).isEmpty()
            || gender.isEmpty() || address.isEmpty() || accountType.isEmpty() || openDate.isEmpty() || amountString.isEmpty() || email.isEmpty()) {
       
        JOptionPane.showMessageDialog(this, "All fields are required");
    } else {
        try {
            int id = Integer.parseInt(accountNo);
            theAccount.setAccount_nbr(id);
            theAccount.setPin(new String(pin));
            theAccount.setFirst_name(firstName);
            theAccount.setLast_name(lastName);
            theAccount.setGender(gender);
            theAccount.setTelNo(telNo);
            theAccount.setAddress(address);
            theAccount.setAccount_type(accountType);
            theAccount.setAmount(Double.parseDouble(amountString));
            theAccount.setEmail(email);

        
            if (firstName.length() < 2 || lastName.length() < 2) {
                JOptionPane.showMessageDialog(this, "First name and last name must be at least 2 characters long");
                return;
            }
            
            if (!telNo.matches("\\d{3}-\\d{3}-\\d{4}")) {
                JOptionPane.showMessageDialog(this, "Invalid telephone number format. Please use ###-###-#### format.");
                return;
            }
            

            if (!telNo.matches("\\d{3}-\\d{3}-\\d{4}")) {
                JOptionPane.showMessageDialog(this, "Invalid telephone number format. Please use ###-###-#### format.");
                return;
            }
            

            if (!accountNo.matches("\\d{8}")) {
                JOptionPane.showMessageDialog(this, "Account number must contain exactly 8 digits");
                return;
            }
            

            String pinString = new String(pin);
         

//            if (pin.length != 4) {
//                JOptionPane.showMessageDialog(this, "PIN must be exactly 4 digits long");
//                return;
//            }

            if (!(pinString.matches(".*[a-z].*") && pinString.matches(".*[A-Z].*") && pinString.matches(".*[@#$%^&+=].*"))) {
                JOptionPane.showMessageDialog(this, "PIN must contain at least one lowercase letter, one uppercase letter, and one special character (@#$%^&+=)");
                return;
            }

            if ("Select".equals(accountType)) {
                JOptionPane.showMessageDialog(this, "Please select an account type");
            }
           
            if (!openDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(this, "Invalid opening date format. Please use YYYY-MM-DD format.");
                return;
            }
            if (!isValidEmail(email)) {
                JOptionPane.showMessageDialog(this, "Invalid email format. Please enter a valid email address.");
                return;
            }

           
            try {
                Double.parseDouble(amountString);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid amount format. Please enter a valid number.");
                return;
            }

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date parsedDate = dateFormat.parse(openDate);
            theAccount.setOpen_date(parsedDate);

            AccountDao Dao = new AccountDao();
            Integer rowAffected = Dao.recordAccount(theAccount);
            if (rowAffected != null) {
                JOptionPane.showMessageDialog(this, "Data Saved!");
            } else {
                JOptionPane.showMessageDialog(this, "Data Not Saved!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid numeric input for account number or amount");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please enter the date in YYYY-MM-DD format.");
        }
    }
    setVisible(false);
    }//GEN-LAST:event_newAccountActionPerformed
    private boolean isValidEmail(String email) {
    // Regular expression pattern for basic email format validation
    String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    return email.matches(emailPattern);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoText;
    private javax.swing.JComboBox<String> accountTypeText;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField amountText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleText;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton maleText;
    private javax.swing.JButton newAccount;
    private javax.swing.JTextField openDateText;
    private javax.swing.JPasswordField pinText;
    private javax.swing.JTextField telText;
    // End of variables declaration//GEN-END:variables
}
