/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import rw.gov.Dao.AccountDao;
import rw.gov.Dao.TransactionDao;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;

/**
 *
 * @author andre
 */
public class UserHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
      DefaultTableModel model = new DefaultTableModel();

    
    private int accountNumber;
    public UserHome(int accountNumber) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        this.accountNumber = accountNumber;
        
        
        initializeTableModel();
        addRows();
        
        String finduser = name.getText();
        
        AccountDao dao = new AccountDao();
        Account searchuser = dao.retrieveAccount(accountNumber);
        
        if(searchuser != null){
          balance.setText(String.valueOf(searchuser.getAmount()));
        }
        else{
            System.out.println("user not found");
        }
        
        
    }
    
    
     public void initializeTableModel() {
        model.addColumn("Date");
        model.addColumn("Transaction_Type");
        model.addColumn("Amount");
        
        balanceTable.setModel(model);
        
     } 
        
     public void addRows() {
        TransactionDao dao = new TransactionDao();
        model.setRowCount(0);
        List<Transaction> transaction = dao.transactionAccount(accountNumber);
        for (Transaction trans : transaction) {
                    model.addRow(new Object[]{
                    new java.sql.Timestamp(trans.getTimestamp().getTime()), // Corrected syntax
                    trans.getType(),
                    trans.getAmount()
              
                });
            }
        }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        balanceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(620, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Statement");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 20));

        jLabel3.setText("Welcome :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 20));

        name.setText("Andrew");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 80, 20));

        jLabel5.setText("Available Balance:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));

        balance.setEditable(false);
        jPanel2.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 90, 30));

        balanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(balanceTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 430, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 500, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JTable balanceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
